mongo-url = "mongodb://mongo1:27017,mongo2:27017,mongo3:27017/teesis?replicaSet=rp0"

elasticsearch-urls = ["http://elasticsearch:9200"]

elasticsearch-user = "elastic"
elasticsearch-password = "j2h2"

elasticsearch-max-conns = 4

elasticsearch-max-seconds = 5

elasticsearch-max-bytes = 8000000

dropped-collections = false

dropped-databases = false
gzip = true
#stats = true
#index-stats = true
#index-as-update = true
verbose = true
#replay = true
resume = false
#resume-name = "default"

namespace-regex = "^teesis"
direct-read-namespaces = ["teesis.search_info_col"]


[[mapping]]
namespace = "teesis.search_info_col"
index = "search"


[[script]]
namespace = "teesis.search_info_col"
script = """
module.exports = function(doc) {
  var newdoc = {
     user_Id : doc.user_Id,
     major : doc.major,
     subject : doc.subject,
     tag : doc.tag,
  }
  return newdoc;
}
"""