version: "3"

volumes:
  mongodb_data_dev: {}
  postgres_data_dev: {}
  elasticsearch:
  grafana_volume:
#    external: true

services:
#  mongo:
#    container_name: mongo
#    image: mongo:latest
#    volumes:
#      - mongodb_data_dev:/data/db
#    restart: always
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: temppw
#
#  mongo-express:
#    container_name: mongo-express
#    image: mongo-express
#    restart: always
#    ports:
#      - "9018:8081"
#    environment:
#      ME_CONFIG_MONGODB_URL: mongodb://root:temppw@host.docker.internal:27017/
#    depends_on:
#      - mongo

  db:
    image: postgres:12.0-alpine
    container_name: postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "eg_user"
      POSTGRES_PASSWORD: "eg_pw"
      POSTGRES_DB: "eg_db"
    ports:
      - "5432:5432"

  #  redis:
  #    image: redis
  #    ports:
  #      - "6379:6379"

  backend:
    container_name: backend
    build:
      context: ./backend
      args:
        DJANGO_ALLOWED_HOSTS: "*"
        DJANGO_SECRET_KEY: "*"
        DJANGO_CORS_ORIGIN_WHITELIST: "*"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/backend/
    expose:
      - 8000
    env_file:
      - ./settings/dev/.env.dev
    depends_on:
      - db
#      - redis

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - "9100:9100"
    restart: always
    deploy:
      mode: global

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    ports:
      - "19093:9093"
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  cadvisor:
    container_name: cadvisor
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /etc/machine-id:/etc/machine-id:ro #디렉토리 오류나서 추가
    ports:
      - "8081:8080"
    restart: always
    privileged: true #디렉토리 오류나서 추가
    deploy:
      mode: global
      restart_policy:
          condition: on-failure

  prometheus:
    image: prom/prometheus:latest
    restart: always
    container_name: prometheus
    ports:
      - "9090:9090"
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana:latest
    restart: always
    user: "472"
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "8082:3000"
    volumes:
      - grafana_volume:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - grafana/config.monitoring

  elasticsearch:
    container_name: elasticsearch
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.16.3
    #    image: elasticsearch:7.16.3
    restart: always
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: j2h2
      discovery.type: single-node

  kibana:
    container_name: kibana
    image: kibana:7.16.3
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

#  logstash:
#    container_name: logstash
#    build:
#      context: logstash/
#      args:
#        ELK_VERSION: 7.16.3
##    image: logstash:7.16.3
#    volumes:
#      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,z
#      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,z
#    ports:
#      - "5001:5001/tcp"
#      - "5001:5001/udp"
#      - "9600:9600"
#    environment:
#      LOGSTASH_JDBC_URL: jdbc:postgresql://postgres:5432/eg_db
#      LOGSTASH_JDBC_DRIVER: org.postgresql.Driver
#      LOGSTASH_JDBC_DRIVER_JAR_LOCATION: /usr/share/logstash/postgresql-42.2.23.jar
#      LOGSTASH_JDBC_USERNAME: eg_user
#      LOGSTASH_JDBC_PASSWORD: eg_pw
#      LOGSTASH_ELASTICSEARCH_HOST: http://elasticsearch:9200
##      LS_JAVA_OPTS: "Xmx256m -Xms256m"
#    depends_on:
#      - elasticsearch
