version: "3"

volumes:
  mongodb_volume: null
  static_volume: null
  media_volume: null

services:
  mongo:
    container_name: mongo
    image: mongo:5-focal
    volumes:
      - mongodb_volume:/data/db
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - ./settings/prod/.env.db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - "9018:8081"
    env_file:
      - ./settings/prod/.env.db
    depends_on:
      - mongo

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  backend:
    container_name: backend
    build:
      context: ./backend
      args:
        DJANGO_ALLOWED_HOSTS: "*"
        DJANGO_SECRET_KEY: "*"
        DJANGO_CORS_ORIGIN_WHITELIST: "*"
    command: gunicorn backend.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/backend/static
      - media_volume:/backend/media
      - ./backend/:/backend/
    expose:
      - 8000
    env_file:
      - ./settings/prod/.env.prod
    depends_on:
      - mongo
      - redis

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:8080"
    volumes:
      - static_volume:/backend/static
      - media_volume:/backend/media
    depends_on:
      - backend
