version: "3"

volumes:
  mongodb_data_dev: {}

services:
  mongo:
    image: mongo
    volumes:
      - mongodb_data_dev:/data/db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: temppw

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "9018:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:temppw@host.docker.internal:27017/
    depends_on:
      - mongo

  redis:
    container_name: redis
    image: redis
    environment:
      - REDIS_USER=guest
      - REDIS_PASSWORD=guest
    ports:
      - "6379:6379"
    restart: always

  celery:
    image: django
    working_dir: /backend/
    command: celery -A backend worker -l info
    volumes:
      - ./backend/:/backend/
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis

  backend:
    build:
      context: ./backend
      args:
        DJANGO_ALLOWED_HOSTS: "*"
        DJANGO_SECRET_KEY: "*"
        DJANGO_CORS_ORIGIN_WHITELIST: "*"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/backend/
    expose:
      - 8000
    env_file:
      - ./settings/dev/.env.dev
    depends_on:
      - mongo
      - redis